language: python
dist: focal

python:
  - 3.7

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - python3-pip

branches:
  only:
    - master

before_script:
  - python --version
  - sudo python3 -m pip install pylint
  - export LARGE=1

script:
  - make check
  - make test

after_success:
  - echo "success"
 
after_failure:
  - echo "failure"
